### ISSUE TITLE
Docker (2) -- 部署

### ISSUE THREAD

**Issue by zhuqiandai** [zhuqiandai/blogs#29]
```yml
version: '3.9'
services:
  web:
    image: nginx
    container_name: tower_nginx
    ports:
      - 80:80
    volumes:
      - ${HOME}/Docker/nginx/html/:/usr/share/nginx/html
      - ${HOME}/Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  server:
    image: zhuqiandai/nestjs
    container_name: tower_server
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/Docker/server:/server
    command: ["node", "dist/main.js"]

  db:
    image: postgis/postgis:14-master
    container_name: tower_postgres
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/Docker/postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  geoserver:
    image: tomcat:9.0
    container_name: tower_tomcat
    ports:
      - 8888:8080
    volumes:
      # todo: 提取 geoserver conf
      - ${HOME}/Docker/tomcat/webapps/:/usr/local/tomcat/webapps
```

### docker 总结

1. 主要概念为 image -> layer -> container

   使用 image 镜像创建需要的 container，每一个 container 都有独立的 文件系统、环境变量和其他配置

   > docker ps -a
   > docker images

   在配置 Dockerfile 之后，使用 docker build 命令构建一个 image

   > 如果需要推送到 docker hub 上，记得使用 docker tag <container> zhuqiandai/<container> 取一个别名，再使用 docker push 推送

2. container

   使用 volumes -v 配置外部卷，将 container 内部的配置提取到外部

   使用 docker exec -it <container> bash 在 container 内部使用命令行

   多个 container 需要在同一个 network 下互相通信，可以使用 docker network 创建 network，默认也会创建

3. docker compose

   如上，组合多个镜像

   使用 docker-compose up & docker-compose down
